### PR TITLE
Running full make.bash for bootstrapping platforms

### PR DESCRIPTION
**Pull request by oxtoacart**
For some reason, using go tool dist didn't work for me on an OS X host and Go 1.3.3.  When cross-compiling using gox, it complained that the target platforms still needed to be bootstrapped.

So, I changed the code to instead run ./make.bash --no-clean as described in [your blog](https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/) and that took care of the problem.

### CODE REVIEW

**Comment by oxtoacart** [comment]
I just tried it again, and it worked.  The only thing that I can think of that changed is that I'm targeting go 1.4 now.  Since it works on the go version that I need, I'm good to go.  Thanks!

**Comment by oxtoacart** [comment]
@inconshreveable Sorry, that last test of mine was bad - my path was still pointing at my patched gonative.

I just tried this with the latest gonative.  I built go using:

```
gonative -version="1.4" -platforms="darwin_amd64 linux_386 linux_amd64 windows_386"
```

Then I tried to build [flashlight](https://github.com/getlantern/flashlight) and encountered the error:

```
➜  flashlight git:(master) ✗ gox -osarch="linux/386 linux/amd64 windows/386 darwin/amd64"
Number of parallel builds: 4

-->       linux/386: github.com/getlantern/flashlight
-->     linux/amd64: github.com/getlantern/flashlight
-->     windows/386: github.com/getlantern/flashlight
-->    darwin/amd64: github.com/getlantern/flashlight

2 errors occurred:
--> windows/386 error: exit status 3
Stderr: go tool: no such tool "8g"

--> linux/386 error: exit status 3
Stderr: go tool: no such tool "8g"
```

It's possible that this happens when trying to build something with cgo dependencies ...

**Comment by inconshreveable** [comment]
Weird. Alright, I'll take a look again when I have some spare time.

**Comment by oxtoacart** [comment]
Thanks!

**Comment by tucksaun** [comment]
Hi guys,

First thanks @inconshreveable for your work.

So I just ran into the same issue here, manually applying the patch of this PR fix it.
So I would say :+1: for this fix.
For the record I don't use any cgo in our project, but maybe some of our dependencies are.

**Pull request closed without merging**
